export const Mutations = {
  STORE_ANALYSIS: 'STORE_ANALYSIS',
  STORE_PROJECTS: 'STORE_PROJECTS',
}

export const Actions = {
  LOAD_PROJECTS_HOME_PAGE: 'LOAD_PROJECTS_HOME_PAGE',
  FETCH_ANALYSIS_BY_IDS: 'FETCH_ANALYSIS_BY_IDS',
  FETCH_PROJECTS: 'FETCH_PROJECTS'
}