export const Mutations = {
  STORE_PROJECT_METRICS: 'STORE_PROJECT_METRICS',
  ADD_PROJECT: 'ADD_PROJECT',
  ADD_ANALYSIS: 'ADD_ANALYSIS',
  ADD_ANALYSIS_METRICS: 'ADD_ANALYSIS_METRICS',
  ADD_FLOWS: 'ADD_FLOWS',
  ADD_FLOW: 'ADD_FLOW',
  ADD_INTERACTIONS: 'ADD_INTERACTIONS',
  ADD_REQUEST: 'ADD_REQUEST',
  ADD_RESPONSE: 'ADD_RESPONSE',
}

export const Actions = {
  LOAD_PROJECTS_VIEW_PAGE: 'LOAD_PROJECTS_VIEW_PAGE',
  LOAD_PROJECT_OVERVIEW_PAGE: 'LOAD_PROJECT_OVERVIEW_PAGE',
  LOAD_PROJECT_VIEW_PAGE: 'LOAD_PROJECT_VIEW_PAGE',
  LOAD_FLOW_PAGE_VIEW: 'LOAD_FLOW_PAGE_VIEW',
  FETCH_PROJECT_BY_ID: 'FETCH_PROJECT_BY_ID',
  FETCH_ANALYSIS_BY_ID: 'FETCH_ANALYSIS_BY_ID',
  FETCH_ANALYSIS_METRICS_BY_ID: 'FETCH_ANALYSIS_METRICS_BY_ID',
  FETCH_FLOWS_BY_ANALYSIS_ID: 'FETCH_FLOWS_BY_ANALYSIS_ID',
  FETCH_FLOW_BY_ID: 'FETCH_FLOW_BY_ID',
  FETCH_INTERACTIONS_BY_ANALYSIS_ID: 'FETCH_INTERACTIONS_BY_ANALYSIS_ID',
  FETCH_REQUEST_BY_ID: 'FETCH_REQUEST_BY_ID',
  FETCH_RESPONSE_BY_ID: 'FETCH_RESPONSE_BY_ID',
}