export const Mutations = {
  STORE_ANALYSIS: 'STORE_ANALYSIS',
  STORE_PROJECTS: 'STORE_PROJECTS',
  ADD_PROJECT: 'ADD_PROJECT',
  ADD_ANALYSIS: 'ADD_ANALYSIS',
  ADD_FLOWS: 'ADD_FLOWS',
  SELECT_PROJECT_MENU: 'SELECT_PROJECT_MENU'
}

export const Actions = {
  LOAD_PROJECTS_DASHBOARD_PAGE: 'LOAD_PROJECTS_DASHBOARD_PAGE',
  LOAD_PROJECT_DASHBOARD_PAGE: 'LOAD_PROJECT_DASHBOARD_PAGE',
  LOAD_PROJECT_MENU_PAGE: 'LOAD_PROJECT_MENU_PAGE',
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  FETCH_PROJECT_BY_ID: 'FETCH_PROJECT_BY_ID',
  FETCH_ANALYSIS_BY_IDS: 'FETCH_ANALYSIS_BY_IDS',
  FETCH_ANALYSIS_BY_ID: 'FETCH_ANALYSIS_BY_ID',
  FETCH_FLOWS_BY_IDS: 'FETCH_FLOWS_BY_IDS',
}